services:

  backend:
    build:
      context: ./PaperBull-Backend
    container_name: paperbull-backend
    ports:
      - "4000:4000"
    restart: always

  frontend:
    build:
      context: ./PaperBull-Frontend
    container_name: paperbull-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  stoploss:
    build:
      context: ./AlgoTrading
    container_name: stoploss-engine
    command: node stoploss-engine/stoploss.js
    restart: always

  intraday:
    build:
      context: ./AlgoTrading
    container_name: intraday-squareoff
    command: node intradaySquareOff.js
    restart: always