"""
indicators.py
-------------
Phase 2 – Feature Engineering.

Computes the following technical indicators from raw OHLCV data:

    • SMA 10, SMA 20
    • EMA 10, EMA 20
    • RSI (14-period)
    • MACD and MACD Signal line
    • Bollinger Bands (Upper / Lower, 20-period, 2σ)
    • ATR – Average True Range (14-period)

All calculations are done with pandas rolling operations (no ta-lib
dependency required) so the project stays lightweight and transparent.
"""

import pandas as pd
import numpy as np


# ─────────────────────────────────────────────────────────────────────────────
# Individual indicator functions
# ─────────────────────────────────────────────────────────────────────────────

def compute_sma(series: pd.Series, window: int) -> pd.Series:
    """Simple Moving Average over ``window`` periods."""
    return series.rolling(window=window, min_periods=window).mean()


def compute_ema(series: pd.Series, window: int) -> pd.Series:
    """Exponential Moving Average over ``window`` periods."""
    return series.ewm(span=window, adjust=False).mean()


def compute_rsi(series: pd.Series, period: int = 14) -> pd.Series:
    """Relative Strength Index.

    RSI = 100 − 100 / (1 + RS)
    where RS = average_gain / average_loss over ``period`` days.
    """
    delta = series.diff()
    gain  = delta.clip(lower=0)
    loss  = -delta.clip(upper=0)

    # Wilder's smoothing (equivalent to EMA with alpha = 1/period)
    avg_gain = gain.ewm(alpha=1.0 / period, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1.0 / period, adjust=False).mean()

    rs  = avg_gain / avg_loss.replace(0, np.nan)   # avoid div/0
    rsi = 100 - (100 / (1 + rs))
    return rsi


def compute_macd(
    series: pd.Series,
    fast: int = 12,
    slow: int = 26,
    signal: int = 9,
) -> tuple[pd.Series, pd.Series]:
    """MACD line and Signal line.

    Returns
    -------
    macd_line   : EMA(fast) − EMA(slow)
    signal_line : EMA(macd_line, signal)
    """
    ema_fast   = compute_ema(series, fast)
    ema_slow   = compute_ema(series, slow)
    macd_line  = ema_fast - ema_slow
    signal_line = compute_ema(macd_line, signal)
    return macd_line, signal_line


def compute_bollinger_bands(
    series: pd.Series,
    window: int = 20,
    num_std: float = 2.0,
) -> tuple[pd.Series, pd.Series]:
    """Bollinger Bands.

    Returns
    -------
    upper : SMA + num_std × rolling_std
    lower : SMA − num_std × rolling_std
    """
    sma = compute_sma(series, window)
    std = series.rolling(window=window, min_periods=window).std()
    upper = sma + num_std * std
    lower = sma - num_std * std
    return upper, lower


def compute_atr(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    period: int = 14,
) -> pd.Series:
    """Average True Range.

    True Range = max(H-L, |H-Prev_C|, |L-Prev_C|)
    ATR        = Wilder EMA of True Range
    """
    prev_close = close.shift(1)
    tr = pd.concat(
        [
            high - low,
            (high - prev_close).abs(),
            (low  - prev_close).abs(),
        ],
        axis=1,
    ).max(axis=1)
    atr = tr.ewm(alpha=1.0 / period, adjust=False).mean()
    return atr


# ─────────────────────────────────────────────────────────────────────────────
# Master function: add all indicators to DataFrame
# ─────────────────────────────────────────────────────────────────────────────

def add_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Compute all technical indicators and append them to ``df``.

    Parameters
    ----------
    df : Raw OHLCV DataFrame with columns Open, High, Low, Close, Volume
         and a DatetimeIndex.

    Returns
    -------
    pd.DataFrame with 15 feature columns (original OHLCV + 10 indicators).
    NaN rows generated by look-back windows are **not** dropped here;
    that is handled in preprocess.py.
    """
    df = df.copy()

    close = df["Close"]
    high  = df["High"]
    low   = df["Low"]

    # ── Moving averages ───────────────────────────────────────────────────────
    df["SMA_10"] = compute_sma(close, 10)
    df["SMA_20"] = compute_sma(close, 20)
    df["EMA_10"] = compute_ema(close, 10)
    df["EMA_20"] = compute_ema(close, 20)

    # ── Momentum ──────────────────────────────────────────────────────────────
    df["RSI"] = compute_rsi(close, 14)

    # ── Trend ─────────────────────────────────────────────────────────────────
    df["MACD"], df["MACD_Signal"] = compute_macd(close)

    # ── Volatility ────────────────────────────────────────────────────────────
    df["BB_Upper"], df["BB_Lower"] = compute_bollinger_bands(close, 20, 2.0)
    df["ATR"] = compute_atr(high, low, close, 14)

    print(f"[indicators.py] Features computed. DataFrame shape: {df.shape}")
    return df


# ─────────────────────────────────────────────────────────────────────────────
# Quick smoke-test
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    from data import download_stock_data
    import config

    raw = download_stock_data(config.TICKER, config.START_DATE, config.END_DATE)
    featured = add_indicators(raw)
    print(featured[["Close", "SMA_20", "RSI", "MACD", "BB_Upper", "ATR"]].tail(10))
