import "../Styles/PolicyPages.css";
import { Link } from "react-router-dom";

const Disclaimer = () => {
  const lastUpdated = "March 22, 2025";

  return (
    <div className="policy-page">
      <div className="policy-container">
        <div className="policy-header">
          <div className="policy-badge">Legal</div>
          <h1 className="policy-title">Disclaimer</h1>
          <p className="policy-meta">
            Last updated: <span>{lastUpdated}</span> · Important — please read before using PaperBull
          </p>
        </div>

        <div className="policy-intro">
          <p>
            This Disclaimer applies to all content, features, services, and information provided on the
            PaperBull platform at{" "}
            <a href="https://paperbullindia.shop" target="_blank" rel="noreferrer">
              paperbullindia.shop
            </a>
            . By accessing or using PaperBull, you acknowledge and agree to the limitations described
            below.
          </p>
        </div>

        <section className="policy-section">
          <h2>1. No Financial, Investment, or Legal Advice</h2>
          <div className="policy-highlight-box danger">
            <strong>⚠️ PaperBull is NOT a financial advisor, broker, or investment platform.</strong>
            <p>
              Nothing on PaperBull — including market data, stock charts, portfolio analysis, AI-generated
              insights, order history, or any other content — constitutes financial advice, investment
              advice, trading advice, legal advice, or any other type of professional advice.
            </p>
          </div>
          <p>
            All information on PaperBull is provided <strong>for educational and entertainment purposes
            only</strong>. You should not make real-world financial decisions based on any content,
            analysis, or simulated results provided by PaperBull.
          </p>
          <p>
            For real investment decisions, please consult with a qualified financial advisor who is
            registered with the <strong>Securities and Exchange Board of India (SEBI)</strong>.
          </p>
        </section>

        <section className="policy-section">
          <h2>2. Simulated Trading Environment</h2>
          <ul>
            <li>
              PaperBull operates an entirely <strong>simulated (paper) trading environment</strong>. All
              portfolio values, gains, losses, and order executions are virtual and fictional.
            </li>
            <li>
              Simulated trading results do <strong>not</strong> guarantee or predict real-world trading
              performance. Market conditions, emotions, liquidity, slippage, and brokerage fees in real
              markets differ significantly.
            </li>
            <li>
              Past virtual performance shown on PaperBull is not indicative of future real-world results.
            </li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>3. Market Data Accuracy</h2>
          <ul>
            <li>
              Stock prices, indices, charts, and other market data displayed on PaperBull are sourced from
              third-party APIs and market data providers. This data may be delayed, inaccurate, or
              incomplete.
            </li>
            <li>
              We make <strong>no warranties</strong> regarding the accuracy, completeness, timeliness,
              or reliability of any market data displayed.
            </li>
            <li>
              Real-time data provided via <strong>WebSocket and Server-Sent Events (SSE)</strong> may
              experience delays, interruptions, or discrepancies due to network conditions or data
              provider outages.
            </li>
            <li>
              Market data should not be used as the sole basis for any actual trading decision.
            </li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>4. AI-Generated Content Disclaimer</h2>
          <div className="policy-highlight-box">
            <strong>AI Disclaimer:</strong> Stock insights, analyses, and reports generated by our
            AI system (powered by Google Gemini) are automatically generated and may contain errors,
            outdated information, or inaccuracies.
          </div>
          <ul>
            <li>AI insights are generated based on patterns in available data and do not reflect expert human financial analysis.</li>
            <li>We do not review or validate individual AI responses for accuracy.</li>
            <li>AI-generated content should be treated as a starting point for your own research, not as definitive guidance.</li>
            <li>PaperBull, its owners, and its AI providers are not responsible for decisions made based on AI-generated content.</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>5. Third-Party Links &amp; Services</h2>
          <p>
            PaperBull integrates with and may link to third-party services including Google Firebase,
            Razorpay, market data providers, and others. We are not responsible for:
          </p>
          <ul>
            <li>The content, accuracy, or privacy practices of third-party websites or services.</li>
            <li>Interruptions or outages in third-party services that affect PaperBull's functionality.</li>
            <li>Any harm or loss caused by your use of third-party services linked from PaperBull.</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>6. Service Availability</h2>
          <ul>
            <li>
              We do not guarantee that PaperBull will be available at all times. The Platform may be
              subject to downtime for maintenance, updates, or due to circumstances beyond our control.
            </li>
            <li>
              Real-time features (WebSocket streams, SSE, live charts) depend on market data providers
              and may be unavailable during off-market hours or outages.
            </li>
            <li>
              We reserve the right to modify, suspend, or discontinue any feature of the Platform at
              any time without prior notice.
            </li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, PaperBull India, its founders, employees,
            and affiliates shall not be liable for any:
          </p>
          <ul>
            <li>Financial loss, real or simulated, arising from reliance on Platform content</li>
            <li>Decision made based on AI-generated recommendations or insights</li>
            <li>Data loss or corruption within your virtual account or portfolio</li>
            <li>Delays, errors, or inaccuracies in market data</li>
            <li>Loss or damage arising from unauthorized access to your account</li>
            <li>Losses incurred due to Platform downtime or service interruptions</li>
          </ul>
          <p>
            You expressly assume all risks associated with your use of the Platform and its content.
          </p>
        </section>

        <section className="policy-section">
          <h2>8. SEBI Compliance Notice</h2>
          <p>
            PaperBull is <strong>not registered with or regulated by the Securities and Exchange Board
            of India (SEBI)</strong> as a stockbroker, investment advisor, or any other registered
            intermediary.
          </p>
          <p>
            All trading activities on PaperBull are purely simulated and do not involve real financial
            instruments. If you intend to invest real money in the stock market, you must use a
            SEBI-registered broker. Visit the{" "}
            <a href="https://www.sebi.gov.in" target="_blank" rel="noreferrer">
              SEBI official website
            </a>{" "}
            for a list of registered intermediaries.
          </p>
        </section>

        <section className="policy-section">
          <h2>9. Indemnification</h2>
          <p>
            By using PaperBull, you agree to indemnify and hold harmless PaperBull India and its
            associates from any claims, damages, losses, or expenses (including legal fees) arising
            from:
          </p>
          <ul>
            <li>Your violation of these disclaimers or our Terms and Conditions</li>
            <li>Your use or misuse of the Platform or its content</li>
            <li>Any infringement of third-party rights by your actions on the Platform</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>10. Acknowledgement</h2>
          <p>
            By using PaperBull, you acknowledge that you have read and understood this Disclaimer, and
            that you agree with and accept its terms. If you do not agree with any part of this
            Disclaimer, please discontinue use of the Platform immediately.
          </p>
        </section>

        <section className="policy-section">
          <h2>11. Contact</h2>
          <p>If you have questions about this Disclaimer, please contact us:</p>
          <div className="policy-contact-card">
            <div><strong>PaperBull India</strong></div>
            <div>Email: <a href="mailto:shashankjanagam04@gmail.com">shashankjanagam04@gmail.com</a></div>
            <div>Website: <a href="https://paperbullindia.shop" target="_blank" rel="noreferrer">paperbullindia.shop</a></div>
          </div>
        </section>

        <div className="policy-footer-nav">
          <Link to="/privacy-policy">Privacy Policy</Link>
          <Link to="/terms">Terms &amp; Conditions</Link>
          <Link to="/cookie-policy">Cookie Policy</Link>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
