name: Deploy Backend to Oracle Instance

on:
  push:
    paths:
      - 'Stockify-Backend/**'
      - 'AlgoTrading/**'
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle Instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_PUBLIC_IP }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SHH_KEY }}
          script: |
            echo "Connected to Oracle Instance"

            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            cd /home/ubuntu/Stockify

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing backend dependencies..."
            cd Stockify-Backend
            npm install

            echo "Restarting backend..."
            pm2 restart Backend || pm2 start server.js --name Backend

            echo "Restarting stoploss engine..."
            cd ../AlgoTrading
            npm install
            pm2 restart intraday-squareoff || pm2 start intradaySquareOff.js --name intraday-squareoff


            cd stoploss-engine
            pm2 restart stoploss || pm2 start stoploss.js --name stoploss

            echo "Restarting squareoff engine..."

            pm2 save
            echo "Backend deployment completed."
