name: Deploy Backend to Azure VM

on:
  push:
    branches:
      - main
      - ec2

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            echo "Connected to Azure VM"

            cd ~/Stockify

            echo "Pulling latest code..."
            git pull origin main

            echo "Building images..."
            docker compose build

            echo "Starting services..."
            docker compose up -d

            echo "Removing unused images..."
            docker image prune -f

            echo "Deployment completed."