name: Deploy Frontend to Oracle Bucket

on:
  push:
    paths:
      - 'Stockify-Frontend/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd Stockify-Frontend
          npm install

      - name: Build frontend
        run: |
          cd Stockify-Frontend
          npm run build

      - name: Install OCI CLI
        run: |
          python3 -m pip install --upgrade pip
          pip3 install oci-cli

      - name: Configure OCI
        run: |
          mkdir -p ~/.oci

          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config

          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
      - name: Debug build output
        run: |
          echo "ROOT:"
          ls -la

          echo "Stockify-Frontend:"
          ls -la Stockify-Frontend

          echo "Build folder:"
          ls -la Stockify-Frontend/build || echo "No build folder"

          echo "Dist folder:"
          ls -la Stockify-Frontend/dist || echo "No dist folder"
      - name: Upload to Oracle Bucket
        run: |
          if [ -d "Stockify-Frontend/build" ]; then
            SRC="Stockify-Frontend/build"
          elif [ -d "Stockify-Frontend/dist" ]; then
            SRC="Stockify-Frontend/dist"
          else
            echo "❌ ERROR: No build output found"
            exit 1
          fi

          echo "Uploading from $SRC"

          oci os object bulk-upload \
            --bucket-name ${{ secrets.OCI_BUCKET_NAME }} \
            --namespace ${{ secrets.OCI_NAMESPACE }} \
            --src-dir "$SRC" \
            --overwrite

